version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    volumes:
      - .:/usr/src/app
    restart: always # What to do if container crashes
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container  
    build: ./backend
    ports:
      - "3333:3333"
    container_name: backend-docker
    volumes:
      - .:/usr/src/app
    restart: always
    links:
      - db
  # Create database container
  db:
    image: mysql:5.7.29
    expose:
      - "3306"
    ports:
      - 3306:3306
    volumes:
      - .:/usr/src/app
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_SORT_BUFFER_SIZE: 1024K
    restart: always