version: '3'
services:
  mysql:
    image: mysql:5.7.29
    expose:
      - "3306"
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_SORT_BUFFER_SIZE: 1024K
  app:
      build: .
      command: npm run dev
      ports: 
        - '3333:3333'
      volumes:
        - .:/user/app